<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKEcclh9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKEcclh9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKEcclh9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKEcclh9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKEcclh9\App_KernelDevDebugContainer([
    'container.build_hash' => 'KEcclh9',
    'container.build_id' => 'da1b7c89',
    'container.build_time' => 1696450227,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKEcclh9');
